// Builds the NavigationBar's install artifacts into client/public/r/:
//   navigation-bar.json — a registry item in the shadcn item format, so
//                         `npx shadcn@latest add <url>` copies the folder,
//                         adds the npm deps, and injects the CSS variables
//   navigation-bar.zip  — the same files plus tokens.css, for people who
//                         will not run a CLI
// Runs before `vite build` and `vite dev` (package.json scripts) so the
// served artifacts can never lag the source. No dependencies: the zip is
// written by hand in STORE mode (no compression — ~120 KB of text).
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { collectVars, NAV_BAR_VAR_INPUTS, renderVarBlock } from "./collect-vars.mjs";

const FOLDER = "client/src/components/navigation-bar";
const OUT_DIR = "client/public/r";
const NPM_DEPS = ["motion", "lucide-react", "clsx", "tailwind-merge"];

/** The files a consumer needs, with the path they land at in their app. */
export function navBarFiles() {
  const folder = readdirSync(FOLDER).filter(f => !f.startsWith(".")).sort();
  const entries = folder.map(name => ({
    src: join(FOLDER, name),
    path: `components/navigation-bar/${name}`,
    type: name.endsWith(".md") || name.endsWith(".css") ? "registry:file" : "registry:component",
  }));
  entries.push({ src: "client/src/theme/glass.css", path: "styles/glass.css", type: "registry:file" });
  return entries;
}

export function buildNavBarRegistry({ outDir = OUT_DIR } = {}) {
  const vars = collectVars(NAV_BAR_VAR_INPUTS);
  if (vars.unresolved.length)
    throw new Error(`unresolved CSS variables: ${vars.unresolved.join(" ")}`);
  const strip = obj =>
    Object.fromEntries(Object.entries(obj).map(([k, v]) => [k.replace(/^--/, ""), v]));
  const files = navBarFiles().map(f => ({
    path: f.path,
    type: f.type,
    // registry:file entries need an explicit target inside the consumer's app.
    ...(f.type === "registry:file" ? { target: `~/${f.path}` } : {}),
    content: readFileSync(f.src, "utf8"),
  }));
  const readme = readFileSync(join(FOLDER, "README.md"), "utf8");
  const manifest = {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "navigation-bar",
    type: "registry:component",
    title: "Navigation Bar",
    description:
      "A glass bottom bar where navigation, actions, and filters share one surface — a tab switcher that blooms into a menu, a centre pill of per-tab actions, an in-place filter, and one utility button that morphs into search or an assistant chat.",
    author: "Rishi Dean <rishidean.com>",
    dependencies: NPM_DEPS,
    registryDependencies: [],
    files,
    cssVars: { light: strip(vars.light), dark: strip(vars.dark) },
    docs: readme.split("\n## ")[1] ? "## " + readme.split("\n## ")[1] : readme,
  };

  const tokens = `/* NavigationBar tokens — generated by scripts/registry/build.mjs from
   client/src/theme/theme.css. Paste into your global CSS or remap. */\n${renderVarBlock(vars)}\n`;
  const zipEntries = [
    ...navBarFiles().map(f => ({ name: f.path, data: readFileSync(f.src) })),
    { name: "styles/navigation-bar.tokens.css", data: Buffer.from(tokens) },
  ];

  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "navigation-bar.json"), JSON.stringify(manifest, null, 2) + "\n");
  writeFileSync(join(outDir, "navigation-bar.zip"), zipStore(zipEntries));
  return { manifest, zipEntries: zipEntries.map(e => e.name) };
}

// ── Minimal ZIP writer (STORE method) ─────────────────────────────────
const CRC_TABLE = new Uint32Array(256).map((_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function dosDateTime(d = new Date(2026, 0, 1)) {
  const time = (d.getHours() << 11) | (d.getMinutes() << 5) | (d.getSeconds() >> 1);
  const date = ((d.getFullYear() - 1980) << 9) | ((d.getMonth() + 1) << 5) | d.getDate();
  return { time, date };
}
export function zipStore(entries) {
  const { time, date } = dosDateTime();
  const locals = [], centrals = [];
  let offset = 0;
  for (const { name, data } of entries) {
    const nameBuf = Buffer.from(name, "utf8");
    const crc = crc32(data);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4); // version needed
    local.writeUInt16LE(0x0800, 6); // utf-8 names
    local.writeUInt16LE(0, 8); // STORE
    local.writeUInt16LE(time, 10);
    local.writeUInt16LE(date, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28);
    locals.push(local, nameBuf, data);
    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(0, 10);
    central.writeUInt16LE(time, 12);
    central.writeUInt16LE(date, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(data.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt16LE(0, 30); // extra
    central.writeUInt16LE(0, 32); // comment
    central.writeUInt16LE(0, 34); // disk
    central.writeUInt16LE(0, 36); // internal attrs
    central.writeUInt32LE(0, 38); // external attrs
    central.writeUInt32LE(offset, 42);
    centrals.push(central, nameBuf);
    offset += local.length + nameBuf.length + data.length;
  }
  const cd = Buffer.concat(centrals);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(0, 4);
  eocd.writeUInt16LE(0, 6);
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(cd.length, 12);
  eocd.writeUInt32LE(offset, 16);
  eocd.writeUInt16LE(0, 20);
  return Buffer.concat([...locals, cd, eocd]);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { manifest, zipEntries } = buildNavBarRegistry();
  console.log(`wrote ${OUT_DIR}/navigation-bar.json (${manifest.files.length} files) and navigation-bar.zip (${zipEntries.length} entries)`);
}
